bank/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'', include('customer.urls')),
    url(r'^employee/', include('employee.urls'))
]

customer/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'customer'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/', views.register, name='register'),
    url(r'^profile/',views.profile, name='profile'),
    url(r'^withdraw/',views.withdraw, name='withdraw'),
    url(r'^amount/',views.amount, name='amount'),
    url(r'^deposit/', views.deposit, name='deposit'),
    url(r'^amount2/', views.amount2, name='amount2'),
    url(r'^transfer/', views.transfer, name='transfer'),
    url(r'^result/',views.result, name='result'),
    url(r'^edit/',views.edit, name='edit'),
]

customer/models.py
import uuid

from decimal import Decimal
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=200,null=True)
    age=models.IntegerField(null=True)
    phone=models.IntegerField(null=True)
    street=models.CharField(max_length=200,null=True)
    city=models.CharField(max_length=200,null=True)
    state=models.CharField(max_length=50,null=True)
    country=models.CharField(max_length=50, default="India")
    pin_code=models.IntegerField(null=True)
    balance=models.DecimalField(max_digits=10,decimal_places=2,verbose_name="Balance")
    account_no=models.CharField(max_length=200,editable=False)

    def __str__(self):
        return str(self.user)

    def acc_no(self):
        acc_no="ACC"+str(self.pk)
        return acc_no

    def get_balance(self,amount ,code):
        amount = Decimal(amount)
        balance = Decimal(self.balance)
        if code == 1:
            if balance > amount:
                balance=balance-amount
                return balance
            else:
                return -1
        else:
            balance=balance+amount
            return balance

customer/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from .models import *

def clean_contact_no(phone):
    try:
        if phone:
            min_length = 10
            max_length = 15
            ph_length=len(str(phone))
            if ph_length < min_length or ph_length > max_length:
                raise ValidationError('Contact number length is not valid!')
    except(ValueError, TypeError):
        raise ValidationError("Please enter a valid contact number!")
    return phone

class CustomerForm(ModelForm):
    phone = forms.IntegerField(validators=[clean_contact_no], widget=forms.NumberInput(attrs={'required': "required"}))

    class Meta:
        model = Customer
        widgets={
            "name": forms.TextInput(attrs={'required': "required"}),
            "age": forms.NumberInput(attrs={'required': "required"}),
            "street": forms.TextInput(attrs={'required': "required"}),
            "city": forms.TextInput(attrs={'required': "required"}),
            "state": forms.TextInput(attrs={'required': "required"}),
            "country": forms.TextInput(attrs={'required': "required"}),
            "pin_code": forms.NumberInput(attrs={'required': "required"}),
            "balance":forms.NumberInput(attrs={'required': "required"}),
        }
        fields=['name','age','phone','street','city','state','country','pin_code','balance']

customer/views.py
from decimal import Decimal
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy

from .forms import CustomerForm
from .models import Customer
from transaction.models import Transaction
# Create your views here.

def index(request):
    if request.user.groups.filter(name='Employee').exists():
        return HttpResponseRedirect(reverse('employee:index'))
    return render(request, "index.html")

@login_required
def register(request):
    user = User.objects.get(username=request.user.username)
    customer = Customer(user=user)
    form=CustomerForm(request.POST or None, instance=customer)
    context = {"customerform": form,
               "form_url": reverse_lazy('customer:register'),
               "type":"register"
               }
    if request.method=="POST":
        #print("success")
        if form.is_valid():
            f=form.save()
            f.account_no=f.acc_no()
            f.save()
            group=get_object_or_404(Group, name='Customer')
            user.groups.add(group)
            return HttpResponseRedirect(reverse('customer:index'))
    return render(request, "register.html", context)

@login_required
def edit(request):
    user = get_object_or_404(User, username=request.user.username)
    customer = get_object_or_404(Customer, user=user)
    form = CustomerForm(request.POST or None, instance=customer)
    context = {"customerform": form,
               "form_url": reverse_lazy('customer:edit'),
               "type":"edit"
               }
    if request.method == "POST":
        # print("success")
        if form.is_valid():
            f = form.save()
            f.account_no = f.acc_no()
            f.save()
            return HttpResponseRedirect(reverse('customer:index'))
    return render(request, "register.html", context)

@login_required
def profile(request):
    user = Customer.objects.filter(user=request.user)
    #print(user)
    context={
        "data":user
    }
    return render(request, 'profile.html', context)

@login_required
def withdraw(request):
    user=Customer.objects.filter(user=request.user)
    #print(user)
    context={
        "set":user
    }
    return render(request, 'withdraw.html', context)

@login_required
def amount(request):
    user=Customer.objects.get(user=request.user)
    t=Transaction(previous_balance=Decimal(user.balance))
    withdraw = request.POST.get('withdraw')
    t.amount=Decimal(withdraw)
    a=user.get_balance(withdraw,1)
    if a==-1:
        messages.error(request, "No Balance!")
    else:
        user.balance=a
    t.current_balance=Decimal(user.balance)
    t.user=request.user
    t.save()
    t.transaction_id = t.get_transaction_id()
    t.type='Withdrawal'
    t.save()
    user.save()
    return HttpResponseRedirect(reverse('customer:profile'))

@login_required
def deposit(request):
    user=Customer.objects.get(user=request.user)
    #print(user.balance)
    context={
        "balance":user.balance
    }
    return render(request, 'deposit.html', context)

@login_required
def amount2(request):
    user = Customer.objects.get(user=request.user)
    t=Transaction(previous_balance=Decimal(user.balance))
    amount= request.POST.get('deposit')
    t.amount = Decimal(amount)
    user.balance=user.get_balance(amount,2)
    t.current_balance = Decimal(user.balance)
    t.user = request.user
    t.save()
    t.transaction_id = t.get_transaction_id()
    t.type='Deposit'
    t.save()
    user.save()
    return HttpResponseRedirect(reverse('customer:profile'))

@login_required
def transfer(request):
    user = Customer.objects.get(user=request.user)
    context = {
        "balance": user.balance
    }
    return render(request, 'transfer.html', context)

@login_required
def result(request):
    user=Customer.objects.get(user=request.user)
    amount=request.POST.get("amount")
    acc=request.POST.get("acc")
    acc=str(acc)
    t = Transaction(previous_balance=Decimal(user.balance))
    t.amount = Decimal(amount)
    user2=Customer.objects.get(account_no=acc)
    u2=User.objects.get(username=user2.user.username)
    print(type(u2))
    amount=Decimal(amount)
    t2 = Transaction(previous_balance=Decimal(user2.balance))
    t2.amount = Decimal(amount)
    a = user.get_balance(amount, 1)
    if a == -1:
        messages.error(request, "No Balance!")
        return HttpResponseRedirect(reverse('customer:profile'))
    else:
        user.balance = a
        user2.balance=user2.get_balance(amount,2)
        user2.save()
        t2.current_balance = Decimal(user2.balance)
        t2.user = u2
        t2.save()
        t2.transaction_id = t2.get_transaction_id()
        t2.type = 'Account Transfer'
        t2.save()
    user.save()
    t.current_balance = Decimal(user.balance)
    t.user = request.user
    t.save()
    t.transaction_id = t.get_transaction_id()
    t.type = 'Account Transfer'
    t.save()
    return HttpResponseRedirect(reverse('customer:profile'))

customer/templates/deposit.html
{% extends 'base.html' %}

{% block title %}
    <title>Deposit</title>
{% endblock %}

{% block content %}

<h2>Welcome {{ user.username }}</h2>

    <h3>Current Balance: {{ balance }} /-</h3>
<br>
<form method="post" action="{% url "customer:amount2" %}">
{% csrf_token %}
Amount to deposit:<input type="number" name="deposit" id="deposit"/><br>
<input type="submit" value="Submit"/>
</form>

{% endblock %}

customer/templates/index.html
{% extends 'base.html' %}

{% block title %}
    <title>Homepage</title>
{% endblock %}

{% block content %}
    <ul>
    {% if user.is_authenticated %}
        <h3>Welcome {{ user.username }}</h3>
        <h4>Services</h4>
        <li><a href="{% url "customer:edit" %}">Edit Profile</a></li>
        <li><a href="{% url "customer:withdraw" %}">Withdraw Cash</a></li>
        <li><a href="{% url "customer:deposit" %}">Deposit Cash</a></li>
        <li><a href="{% url "customer:transfer" %}">Account Transfer</a></li>
        {% else %}
        <li><a href="{% url "account_login" %}">Login</a></li>
        <li><a href="{% url "account_signup" %}">Customer Signup</a></li>
        <li><a href="{% url "account_signup" %}">Employee Signup</a></li>
    {% endif %}
    </ul>
{% endblock %}

customer/templates/profile.html
{% extends 'base.html' %}

{% block title %}
    <title>Profile</title>
{% endblock %}

{% block content %}

    {% for i in data %}
    <p>Name:<b>{{ i.name }}</b>  <br>
    </p>
    <p>Age: <b>{{ i.age }}</b> <br>
    </p><p>Phone:  <b>{{ i.phone }}</b><br>
    </p><p>Street:  <b>{{ i.street }}</b><br>
    </p><p>City:  <b>{{ i.city }}</b><br>
    </p><p>Country:  <b>{{ i.country }}</b><br>
    </p><p>account_no: <b> {{ i.account_no }}</b><br>
    </p>
        <h3>Balance: {{ i.balance }} /-</h3>
    {% endfor %}

{% endblock %}

customer/templates/register.html
{% extends 'base.html' %}

{% block title %}
    <title>Register</title>
{% endblock %}

{% block content %}

    <h2>Welcome {{ user.username }}</h2>
<h2>Registeration</h2>
    <form method="post" action="{{ form_url }}" >
{% csrf_token %}
        <table>
            {{ customerform }}
        </table>

<tr><td><input type="submit" value="{% if not type == "edit" %}Submit{% else %}Update{% endif %}" name="submit"/></td></tr>
</form>

{% endblock %}

customer/templates/transfer.html
{% extends 'base.html' %}

{% block title %}
    <title>Account Transfer</title>
{% endblock %}

{% block content %}

<h2>Welcome {{ user.username }}</h2>

    <h3>Current Balance: {{ balance }} /-</h3><br>

<form method="post" action="{% url 'customer:result' %}">
{% csrf_token %}
<table>
    <tr><td>Amount to transfer:</td><td><input type="number" name="amount" id="amount"/></td></tr>
    <tr><td>Input Account Number:</td><td><input type="text" name="acc" id="acc"/></td></tr>
    <tr><td></td><td><input type="submit" value="Submit"/></td></tr>
</table>
</form>

{% endblock %}

customer/templates/withdraw.html
{% extends 'base.html' %}

{% block title %}
    <title>Withdrawal</title>
{% endblock %}

{% block content %}

<h2>Welcome {{ user.username }}</h2>
    {% for user in set %}
    <h3>Current Balance: {{ user.balance }} /-</h3><br>
{% endfor %}
<form method="post" action="{% url "customer:amount" %}">
{% csrf_token %}
Amount to withdraw:<input type="number" name="withdraw" id="withdraw"/><br>
<input type="submit" value="Submit"/>
</form>

{% endblock %}